name: BananaGen
main: net.llamaslayers.minecraft.banana.gen.GenPlugin
version: 0.1
authors:
    - Nightgunner5
    - Dinnerbone
    - codename_B
    - SpaceManiac
load: startup
commands:
    bananaworld:
        usage: /bananaworld <world> [player]
    bananagen:
        usage: /bananagen <radius> [<x> <z>] [world]
    bananaregen:
        usage: /bananaregen <radius>
permissions:
    bananagen.world.self:
        default: true
    bananagen.world.other:
        default: op
    bananagen.generate:
        default: op
    bananagen.regenerate:
        default: op